apiVersion: apps/v1
kind: Deployment
metadata:
  name: moment-one-deployment
spec: 
  replicas: 1
  template: 
    metadata:
      labels:
        app: moment-one
    spec:
      containers:
        - name: moment-one
          image: sabin2000/moment-one