      # Version: 3
      # The services section defines the name of the service that will be used to build the docker file, in this case Web.

      # Author: Sabin Constantin Lungu

version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sabin2000/momentone
    restart: always
    ports: 
      - "8001:8001"
    volumes: 
      - /app/node_modules
      - .:/app
  mongo:
    image: mongo
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGO_DB_ROOT_USERNAME: admin
      MONGO_DB_ROOT_PASSWORD: N@p1er123